"""Protocol layer: pure data models, enums, and event contracts.

This package is shared by Core, TUI, and CLI layers. It has zero UI
dependencies and defines the strict communication contract.
"""

from .enums import (
    AttemptDisposition,
    BackendType,
    CachePolicy,
    CleanupDisposition,
    DeploymentState,
    EvidenceLevel,
    MemoryObservationSource,
    OperationIntent,
    OperationType,
    OutcomeKind,
    SpeculativeDecodingMethod,
)
from .events import (
    BaseEvent,
    EndpointAvailableEvent,
    ErrorEvent,
    LogEvent,
    OperationCompleteEvent,
    ResourceAllocatedEvent,
    StateChangeEvent,
)
from .models import (
    BINARY_GIB,
    DECIMAL_GB,
    VAST_DISPLAY_GB,
    VAST_RAW_MIB,
    CompatibilityEvidence,
    CostEvaluation,
    DeploymentAttemptOutcome,
    DeploymentConfig,
    DeploymentRequest,
    DeploymentResult,
    EndpointInfo,
    EvaluationRecord,
    LaunchpadSettings,
    LlamacppRequestOptions,
    MemoryObservation,
    MemoryUnits,
    PerformancePoint,
    PredictionSnapshot,
    ReasoningCapabilities,
    ResolvedDeploymentPlan,
    RuntimeIdentity,
    SpeculativeDecodingConfig,
    StoredModelInfo,
    StorageSnapshot,
    VllmRequestOptions,
    WorkloadScenario,
    convert_memory,
    vast_raw_mib_to_display_gb,
)

__all__ = [
    "BINARY_GIB",
    "AttemptDisposition",
    "BackendType",
    "BaseEvent",
    "CachePolicy",
    "CleanupDisposition",
    "CompatibilityEvidence",
    "CostEvaluation",
    "DECIMAL_GB",
    "DeploymentAttemptOutcome",
    "DeploymentConfig",
    "DeploymentRequest",
    "DeploymentResult",
    "DeploymentState",
    "EndpointAvailableEvent",
    "EndpointInfo",
    "ErrorEvent",
    "EvaluationRecord",
    "EvidenceLevel",
    "LaunchpadSettings",
    "LlamacppRequestOptions",
    "LogEvent",
    "MemoryObservation",
    "MemoryObservationSource",
    "MemoryUnits",
    "OperationCompleteEvent",
    "OperationIntent",
    "OperationType",
    "OutcomeKind",
    "PerformancePoint",
    "PredictionSnapshot",
    "ReasoningCapabilities",
    "ResolvedDeploymentPlan",
    "ResourceAllocatedEvent",
    "RuntimeIdentity",
    "SpeculativeDecodingConfig",
    "SpeculativeDecodingMethod",
    "StateChangeEvent",
    "StoredModelInfo",
    "StorageSnapshot",
    "VAST_DISPLAY_GB",
    "VAST_RAW_MIB",
    "VllmRequestOptions",
    "WorkloadScenario",
    "convert_memory",
    "vast_raw_mib_to_display_gb",
]
