"""Data models shared across the launchpad stack."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional

from .enums import (
    BackendType,
    BillingModel,
    CertificationState,
    ComputeProvider,
    QuoteAvailability,
    ServingObjective,
    SpeculativeDecodingMethod,
)


@dataclass(frozen=True)
class ModalProviderOptions:
    """Modal-specific deployment options kept behind the provider boundary."""


@dataclass(frozen=True)
class PrimeProviderOptions:
    """Prime-specific deployment options kept behind the provider boundary."""

    offer_id: Optional[str] = None
    region: Optional[str] = None
    disk_id: Optional[str] = None
    keep_failed_resource: bool = False
    allow_insecure_http: bool = False
    auto_disk: bool = True


ProviderOptions = ModalProviderOptions | PrimeProviderOptions


@dataclass
class LaunchpadSettings:
    """Persisted user settings (scaledown, appearance, and TUI behavior)."""

    scaledown_window: int = 1800  # seconds (30 minutes)
    tui_theme: str = "launchpad-dark"
    tui_density: str = "comfortable"
    tui_mouse: Optional[bool] = None  # None = follow CLI/env default
    confirm_quit: bool = True

    def to_env(self) -> Dict[str, str]:
        """Derive Modal environment variables from settings."""
        env: Dict[str, str] = {}
        if self.scaledown_window > 0:
            env["SCALEDOWN_WINDOW"] = str(self.scaledown_window)
        return env

    def to_dict(self) -> Dict[str, Any]:
        return {
            "SCALEDOWN_WINDOW": self.scaledown_window,
            "tui_theme": self.tui_theme,
            "tui_density": self.tui_density,
            "tui_mouse": self.tui_mouse,
            "confirm_quit": self.confirm_quit,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> LaunchpadSettings:
        raw_value = data.get("SCALEDOWN_WINDOW", data.get("scaledown_window", 1800))
        raw_mouse = data.get("tui_mouse")
        mouse = raw_mouse if isinstance(raw_mouse, bool) else None
        return cls(
            scaledown_window=int(raw_value),
            tui_theme=str(data.get("tui_theme", "launchpad-dark")),
            tui_density=str(data.get("tui_density", "comfortable")),
            tui_mouse=mouse,
            confirm_quit=bool(data.get("confirm_quit", True)),
        )


@dataclass(frozen=True)
class ReasoningCapabilities:
    """Verified model reasoning controls advertised to API clients."""

    profile_id: str
    canonical_model_id: str
    model_revision: str
    efforts: tuple[str, ...]
    default_effort: str
    source_repo: str
    source_revision: str
    source_path: str
    request_option_path: str
    enable_thinking: bool = True
    interleaved_field: Optional[str] = None


@dataclass(frozen=True)
class SpeculativeDecodingConfig:
    """A verified speculative-decoding recommendation or deployment request."""

    method: SpeculativeDecodingMethod
    num_speculative_tokens: int
    nextn_predict_layers: Optional[int] = None


@dataclass(frozen=True)
class ServingRequirements:
    """Hard serving constraints plus the preferred optimization objective."""

    context_tokens: int
    objective: ServingObjective = ServingObjective.GENERAL_PURPOSE
    full_context_per_request: bool = True
    gpu_only: bool = True
    max_hourly_cost_usd: Optional[float] = None


@dataclass(frozen=True)
class RuntimeTuning:
    """Resolved runtime controls generated by a backend-specific planner."""

    parallel_slots: int = 1
    batch_size: int = 2048
    ubatch_size: int = 512
    cache_type_k: str = "f16"
    cache_type_v: str = "f16"
    flash_attention: bool = True
    gpu_layers: str = "all"
    fit_target_mib: int = 2048
    speculative_decoding: Optional[SpeculativeDecodingConfig] = None


@dataclass(frozen=True)
class MemoryEstimate:
    """Topology-aware memory requirement for one serving configuration."""

    weights_gb: float
    kv_cache_gb: float
    compute_gb: float
    speculative_gb: float
    reserve_gb: float
    total_gb: float
    per_device_required_gb: tuple[float, ...] = ()
    confidence: float = 0.0
    source: str = "estimated"
    total_layer_count: Optional[int] = None


@dataclass(frozen=True)
class PerformancePoint:
    """One measured or predicted point on an endpoint performance curve."""

    prompt_tokens: int
    output_tokens: int
    concurrency: int
    prompt_tokens_per_second: Optional[float] = None
    output_tokens_per_second: Optional[float] = None
    aggregate_output_tokens_per_second: Optional[float] = None
    time_to_first_token_seconds: Optional[float] = None
    p95_latency_seconds: Optional[float] = None
    error_rate: float = 0.0
    output_tokens_per_dollar: Optional[float] = None
    measured: bool = False


@dataclass(frozen=True)
class PlacementAssessment:
    """Planner evidence that a provider placement can satisfy a recipe."""

    fingerprint: str
    memory: MemoryEstimate
    tuning: RuntimeTuning
    performance: tuple[PerformancePoint, ...] = ()
    certification: CertificationState = CertificationState.ESTIMATED
    fits: bool = False
    gpu_resident: bool = False
    rejection_reason: Optional[str] = None


@dataclass(frozen=True)
class RuntimeAttestation:
    """Observed runtime configuration and performance for a live endpoint."""

    fingerprint: str
    requested_context_tokens: int
    effective_context_tokens: int
    gpu_layers: int
    total_layers: int
    gpu_resident: bool
    memory: Optional[MemoryEstimate] = None
    performance: tuple[PerformancePoint, ...] = ()
    runtime_id: Optional[str] = None
    verified_at: Optional[str] = None


@dataclass
class DeploymentConfig:
    """All parameters needed to execute a deployment."""

    backend: BackendType = BackendType.LLAMACPP
    provider: ComputeProvider = ComputeProvider.MODAL

    # llama.cpp specific
    preset: Optional[str] = None
    repo_id: Optional[str] = None
    quant: Optional[str] = None
    revision: Optional[str] = None
    preload: bool = True
    server_args: Optional[str] = None
    host: Optional[str] = None
    port: Optional[int] = None
    n_gpu_layers: Optional[int] = None
    llamacpp_image_no_cache: Optional[bool] = None
    gpu_type: Optional[str] = None
    gpu_count: Optional[int] = None
    required_vram_gb: Optional[float] = None
    gguf_architecture: Optional[str] = None
    llamacpp_runtime_id: Optional[str] = None
    speculative_decoding: Optional[SpeculativeDecodingConfig] = None
    serving_requirements: Optional[ServingRequirements] = None
    runtime_tuning: Optional[RuntimeTuning] = None
    placement_assessment: Optional[PlacementAssessment] = None
    runtime_attestation: Optional[RuntimeAttestation] = None

    # Model limits advertised to OpenAI-compatible clients such as OpenCode.
    max_context_tokens: Optional[int] = None
    max_output_tokens: Optional[int] = None
    reasoning: Optional[ReasoningCapabilities] = None

    # vLLM specific
    model_name: Optional[str] = None
    model_revision: Optional[str] = None
    served_model_name: Optional[str] = None
    fast_boot: Optional[bool] = None
    n_gpu: Optional[int] = None
    trust_remote_code: Optional[bool] = None
    reasoning_parser: Optional[str] = None
    tool_call_parser: Optional[str] = None
    default_chat_template_kwargs: Optional[str] = None

    # Deployment options
    do_deploy: bool = True
    run_smoke: bool = False
    do_warmup: bool = True
    show_debug_logs: bool = False

    # Instance identity
    instance_name: Optional[str] = None
    app_name: Optional[str] = None
    function_slug: Optional[str] = None

    # Provider-specific settings are typed and interpreted only by the adapter.
    provider_options: Optional[ProviderOptions] = None
    endpoint_api_key: Optional[str] = None
    # Ephemeral Fast Deploy recovery ladder. Provider adapters ignore it.
    fallback_configs: tuple[DeploymentConfig, ...] = ()


@dataclass(frozen=True)
class ProviderCapabilities:
    """Provider features used to filter recipes before requesting quotes."""

    provider: ComputeProvider
    supported_backends: frozenset[BackendType]
    billing_model: BillingModel
    live_availability: bool = False
    supports_regions: bool = False
    supports_spot: bool = False
    supports_secure_cloud: bool = False

    def supports_backend(self, backend: BackendType) -> bool:
        """Return whether this provider can serve the requested runtime."""
        return backend in self.supported_backends


@dataclass(frozen=True)
class InferenceRecipe:
    """Provider-neutral description of a runnable inference configuration."""

    id: str
    model_key: str
    display_name: str
    backend: BackendType
    model_id: str
    quant: Optional[str] = None
    max_context_tokens: Optional[int] = None
    required_vram_gb: Optional[float] = None
    server_args: tuple[str, ...] = ()
    speculative_decoding: Optional[SpeculativeDecodingConfig] = None
    source_label: str = "Curated"
    quality_score: Optional[float] = None
    quality_rank: Optional[int] = None
    serving_requirements: Optional[ServingRequirements] = None
    runtime_tuning: Optional[RuntimeTuning] = None


@dataclass(frozen=True)
class WorkloadProfile:
    """Small workload description used to normalize unlike billing models."""

    paid_hours_per_day: float = 8.0
    utilization: float = 0.25
    output_tokens_per_month: Optional[int] = None


@dataclass(frozen=True)
class ProviderQuote:
    """Normalized provider fulfillment option for an inference recipe."""

    id: str
    recipe_id: str
    provider: ComputeProvider
    provider_reference: str
    gpu_type: str
    gpu_count: int
    price_per_hour_usd: Optional[float]
    billing_model: BillingModel
    gpu_memory_gb: Optional[float] = None
    availability: QuoteAvailability = QuoteAvailability.UNKNOWN
    region: Optional[str] = None
    security: Optional[str] = None
    is_estimate: bool = True
    estimated_output_tokens_per_second: Optional[float] = None
    configuration_id: Optional[str] = None
    provider_options: Optional[ProviderOptions] = None
    estimated_prompt_tokens_per_second: Optional[float] = None
    estimated_aggregate_output_tokens_per_second: Optional[float] = None


@dataclass(frozen=True)
class InferencePlan:
    """One deployable recipe bound to a compatible provider quote."""

    recipe: InferenceRecipe
    quote: ProviderQuote
    estimated_monthly_cost_usd: Optional[float] = None
    estimated_cost_per_million_output_tokens_usd: Optional[float] = None
    recommendation_reason: Optional[str] = None
    assessment: Optional[PlacementAssessment] = None


@dataclass(frozen=True)
class ComputePlacement:
    """One provider fulfillment option behind an aggregated GPU type."""

    id: str
    provider: ComputeProvider
    provider_reference: str
    gpu_type: str
    gpu_memory_gb: float
    gpu_count_min: int
    gpu_count_max: int
    price_per_hour_usd: Optional[float]
    billing_model: BillingModel
    availability: QuoteAvailability
    supported_backends: frozenset[BackendType]
    region: Optional[str] = None
    security: Optional[str] = None
    is_estimate: bool = False
    price_is_per_gpu: bool = False
    is_spot: bool = False
    provider_options: Optional[ProviderOptions] = None


@dataclass(frozen=True)
class ComputeConfiguration:
    """Provider-neutral GPU type with all compatible fulfillment placements."""

    id: str
    gpu_type: str
    gpu_memory_gb: float
    placements: tuple[ComputePlacement, ...]

    def _fulfillable_placements(self) -> tuple[ComputePlacement, ...]:
        """Return deployable rows, falling back to spot-only catalogs."""

        deployable = tuple(row for row in self.placements if not row.is_spot)
        return deployable or self.placements

    @property
    def gpu_count_min(self) -> int:
        return min(
            (row.gpu_count_min for row in self._fulfillable_placements()),
            default=1,
        )

    @property
    def gpu_count_max(self) -> int:
        return max(
            (row.gpu_count_max for row in self._fulfillable_placements()),
            default=1,
        )

    @property
    def total_vram_max_gb(self) -> float:
        return self.gpu_memory_gb * self.gpu_count_max

    @property
    def live_placement_count(self) -> int:
        return sum(
            row.availability == QuoteAvailability.AVAILABLE and not row.is_spot
            for row in self.placements
        )

    @property
    def has_on_demand_capacity(self) -> bool:
        return any(
            row.availability == QuoteAvailability.UNKNOWN and not row.is_spot
            for row in self.placements
        )

    @property
    def spot_placement_count(self) -> int:
        return sum(row.is_spot for row in self.placements)

    @property
    def source_count(self) -> int:
        return len({row.provider for row in self.placements})

    @property
    def regions(self) -> tuple[str, ...]:
        return tuple(
            sorted(
                {
                    row.region.strip()
                    for row in self.placements
                    if row.region and row.region.strip()
                },
                key=str.casefold,
            )
        )

    @property
    def minimum_price_per_hour_usd(self) -> Optional[float]:
        prices = [
            row.price_per_hour_usd
            for row in self._fulfillable_placements()
            if row.price_per_hour_usd is not None
        ]
        return min(prices) if prices else None


@dataclass(frozen=True)
class ComputeAvailabilitySnapshot:
    """Aggregated compute availability plus connected provider metadata."""

    configurations: tuple[ComputeConfiguration, ...]
    errors: tuple[str, ...] = ()
    providers: Optional[tuple[ComputeProvider, ...]] = None


@dataclass
class EndpointInfo:
    """A single row from `modal app list`."""

    name: str = ""
    app_id: str = ""
    state: str = "unknown"
    backend: Optional[BackendType] = None
    instance_name: Optional[str] = None
    web_url: Optional[str] = None
    served_model_name: Optional[str] = None
    display_name: Optional[str] = None
    model_name: Optional[str] = None
    repo_id: Optional[str] = None
    quant: Optional[str] = None
    runtime_status: Optional[str] = None
    runtime_status_detail: Optional[str] = None
    provider: ComputeProvider = ComputeProvider.MODAL
    endpoint_api_key: Optional[str] = None
    max_context_tokens: Optional[int] = None
    max_output_tokens: Optional[int] = None
    reasoning: Optional[ReasoningCapabilities] = None
    runtime_attestation: Optional[RuntimeAttestation] = None


@dataclass
class BenchmarkConfig:
    """Parameters for benchmarking a deployed OpenAI-compatible endpoint."""

    backend: BackendType = BackendType.LLAMACPP
    provider: ComputeProvider = ComputeProvider.MODAL
    app_name: Optional[str] = None
    instance_name: Optional[str] = None
    server_url: Optional[str] = None
    model_name: Optional[str] = None
    concurrency: list[int] = field(default_factory=lambda: [1, 2, 4, 8, 16])
    request_count: Optional[int] = None
    input_tokens: int = 550
    output_tokens: int = 256
    tokenizer: str = "gpt2"
    request_timeout_seconds: int = 300
    output_dir: Optional[str] = None
    aiperf_args: list[str] = field(default_factory=list)
    api_key: Optional[str] = None


@dataclass(frozen=True)
class ComputeOffer:
    """Normalized GPU offer exposed by a compute provider."""

    id: str
    cloud_id: str
    provider_name: str
    gpu_type: str
    gpu_count: int
    gpu_memory_gb: Optional[float] = None
    region: Optional[str] = None
    data_center: Optional[str] = None
    country: Optional[str] = None
    socket: Optional[str] = None
    security: Optional[str] = None
    price_per_hour: Optional[float] = None
    is_spot: bool = False
    is_variable_price: bool = False
    stock_status: Optional[str] = None
    disk_default_gb: Optional[int] = None
    vcpu_default: Optional[int] = None
    memory_default_gb: Optional[int] = None
    images: tuple[str, ...] = ()
    raw: dict[str, Any] = field(default_factory=dict, repr=False, compare=False)


@dataclass
class BenchmarkConcurrencyResult:
    """Benchmark result for one concurrency value."""

    concurrency: int
    command: list[str]
    artifact_dir: str
    exit_code: int = 0
    success: bool = True
    detail: str = ""
    json_export_path: Optional[str] = None
    csv_export_path: Optional[str] = None
    metrics: dict[str, Optional[float]] = field(default_factory=dict)


@dataclass
class BenchmarkRunSummary:
    """Summary of a benchmark sweep."""

    config: BenchmarkConfig
    run_dir: str
    results: list[BenchmarkConcurrencyResult] = field(default_factory=list)
    success: bool = True
    best_concurrency: Optional[int] = None
    best_output_token_throughput: Optional[float] = None


@dataclass
class StoredModelInfo:
    """Single cached model entry in Modal storage."""

    backend: BackendType
    model_id: str
    revision: Optional[str] = None
    quant: Optional[str] = None
    size_bytes: int = 0
    file_count: int = 0
    source_volume: str = ""
    paths: list[str] | None = None
    incomplete: bool = False


@dataclass
class StorageSnapshot:
    """Cached model inventory grouped by backend."""

    llamacpp_models: list[StoredModelInfo]
    vllm_models: list[StoredModelInfo]

    @property
    def total_size_bytes(self) -> int:
        return sum(row.size_bytes for row in self.llamacpp_models + self.vllm_models)

    @property
    def total_models(self) -> int:
        return len(self.llamacpp_models) + len(self.vllm_models)
