"""Data models shared across the launchpad stack."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .enums import (
    AttemptDisposition,
    BackendType,
    CachePolicy,
    CleanupDisposition,
    EvidenceLevel,
    MemoryObservationSource,
    OperationIntent,
    OutcomeKind,
    VisionMode,
    VisionVerification,
    BillingModel,
    CertificationState,
    ComputeProvider,
    QuoteAvailability,
    ServingObjective,
    SpeculativeDecodingMethod,
)


@dataclass(frozen=True)
class ModalProviderOptions:
    """Modal-specific deployment options kept behind the provider boundary."""


@dataclass(frozen=True)
class PrimeProviderOptions:
    """Prime-specific deployment options kept behind the provider boundary."""

    offer_id: str | None = None
    region: str | None = None
    disk_id: str | None = None
    keep_failed_resource: bool = False
    allow_insecure_http: bool = False
    auto_disk: bool = True


@dataclass(frozen=True)
class VastProviderOptions:
    """Selected on-demand rental and the maximum approved hourly total."""

    offer_id: str
    disk_gb: int
    max_hourly_cost_usd: float
    machine_id: str | None = None
    # None means the offer's own count is authoritative, which is what the CLI
    # can promise without a lookup. An integer is a shape the user approved,
    # and a rental that no longer matches it is refused like a price increase.
    gpu_count: int | None = None


ProviderOptions = ModalProviderOptions | PrimeProviderOptions | VastProviderOptions


@dataclass
class LaunchpadSettings:
    """Persisted user settings (scaledown, appearance, and TUI behavior)."""

    scaledown_window: int = 1800  # seconds (30 minutes)
    tui_theme: str = "launchpad-dark"
    tui_density: str = "comfortable"
    tui_mouse: bool | None = None  # Legacy setting; ignored by the keyboard-driven TUI
    confirm_quit: bool = True

    def to_env(self) -> dict[str, str]:
        """Derive Modal environment variables from settings."""
        env: dict[str, str] = {}
        if self.scaledown_window > 0:
            env["SCALEDOWN_WINDOW"] = str(self.scaledown_window)
        return env

    def to_dict(self) -> dict[str, Any]:
        return {
            "SCALEDOWN_WINDOW": self.scaledown_window,
            "tui_theme": self.tui_theme,
            "tui_density": self.tui_density,
            "tui_mouse": self.tui_mouse,
            "confirm_quit": self.confirm_quit,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> LaunchpadSettings:
        raw_value = data.get("SCALEDOWN_WINDOW", data.get("scaledown_window", 1800))
        raw_mouse = data.get("tui_mouse")
        mouse = raw_mouse if isinstance(raw_mouse, bool) else None
        return cls(
            scaledown_window=int(raw_value),
            tui_theme=str(data.get("tui_theme", "launchpad-dark")),
            tui_density=str(data.get("tui_density", "comfortable")),
            tui_mouse=mouse,
            confirm_quit=bool(data.get("confirm_quit", True)),
        )


@dataclass(frozen=True)
class ReasoningCapabilities:
    """Verified model reasoning controls advertised to API clients."""

    profile_id: str
    canonical_model_id: str
    model_revision: str
    efforts: tuple[str, ...]
    default_effort: str
    source_repo: str
    source_revision: str
    source_path: str
    request_option_path: str
    enable_thinking: bool = True
    interleaved_field: str | None = None


@dataclass(frozen=True)
class ProjectorArtifact:
    """A revision-pinned Hugging Face vision projector."""

    repo_id: str
    revision: str
    filename: str
    size_bytes: int | None = None


@dataclass
class VisionCapabilities:
    """Model evidence and effective deployment image input state."""

    supported: bool | None = None
    enabled: bool = False
    model_revision: str | None = None
    runtime_id: str | None = None
    projector: ProjectorArtifact | None = None
    verification: VisionVerification = VisionVerification.UNTESTED
    message: str = "Image capability has not been inspected."
    fingerprint: str = ""


@dataclass(frozen=True)
class SpeculativeDecodingConfig:
    """A verified speculative-decoding recommendation or deployment request."""

    method: SpeculativeDecodingMethod
    num_speculative_tokens: int
    nextn_predict_layers: int | None = None


@dataclass(frozen=True)
class ServingRequirements:
    """Hard serving constraints plus the preferred optimization objective."""

    context_tokens: int
    objective: ServingObjective = ServingObjective.GENERAL_PURPOSE
    full_context_per_request: bool = True
    gpu_only: bool = True
    max_hourly_cost_usd: float | None = None


@dataclass(frozen=True)
class RuntimeTuning:
    """Resolved runtime controls generated by a backend-specific planner."""

    parallel_slots: int = 1
    batch_size: int = 2048
    ubatch_size: int = 512
    cache_type_k: str = "f16"
    cache_type_v: str = "f16"
    flash_attention: bool = True
    gpu_layers: str = "all"
    fit_target_mib: int = 2048
    speculative_decoding: SpeculativeDecodingConfig | None = None


@dataclass(frozen=True)
class MemoryEstimate:
    """Topology-aware memory requirement for one serving configuration.

    Weights, KV cache and speculative buffers shard across the devices of a
    placement. ``compute_gb`` and ``attention_scratch_gb`` do not: every device
    builds its own graph, so each one pays them in full. ``total_gb`` already
    counts them once per device, which keeps ``total_gb / gpu_count`` the
    per-device requirement.
    """

    weights_gb: float
    kv_cache_gb: float
    compute_gb: float
    speculative_gb: float
    reserve_gb: float
    total_gb: float
    per_device_required_gb: tuple[float, ...] = ()
    confidence: float = 0.0
    source: str = "estimated"
    total_layer_count: int | None = None
    # Scores and mask of a graph built without flash attention. Zero whenever
    # flash attention is on, and linear in the advertised context when it is
    # off, which is the term that decides whether a long context is servable.
    attention_scratch_gb: float = 0.0
    # Recurrent state is included in kv_cache_gb; retain its contribution so
    # changing concurrency can resize state without scaling the token cache.
    recurrent_gb: float = 0.0
    recurrent_state_copies: int = 1


@dataclass(frozen=True)
class CatalogExclusion:
    """A discovered model omitted from Fast Deploy, with a reviewable reason."""

    model_id: str
    display_name: str
    repo_id: str
    reason: str
    rank: int | None = None
    #: Whether the build reached no conclusion about this model, as opposed to
    #: deciding against it. A rate limit, an exhausted request budget and an
    #: unreachable Hub all leave the model unchecked, and that is a transient
    #: fact about the build rather than a durable one about the model. Readers
    #: that treat a shorter catalog as complete -- the freshness check, the
    #: retention guard, the screen's own status line -- key off this instead
    #: of matching one reason string each.
    unchecked: bool = False


@dataclass(frozen=True)
class PerformancePoint:
    """One measured or predicted point on an endpoint performance curve.

    Metric semantics are fixed so predictions and observations are comparable:

    - ``prompt_tokens``/``output_tokens`` are counted model tokens, never
      repeated prompt filler or streaming chunks.
    - ``output_tokens_per_second`` is a per-request decode rate: generated
      tokens divided by decode time after the first token.
    - ``aggregate_output_tokens_per_second`` is end-to-end: all generated
      tokens across the scenario divided by scenario wall time, including
      prefill, overhead, and failures to start.
    - ``time_to_first_token_seconds`` runs from request dispatch to the first
      generated token.
    - ``p95_latency_seconds`` is only meaningful with enough samples
      (``sample_count`` records how many); small samples leave it None.
    """

    prompt_tokens: int
    output_tokens: int
    concurrency: int
    prompt_tokens_per_second: float | None = None
    output_tokens_per_second: float | None = None
    aggregate_output_tokens_per_second: float | None = None
    time_to_first_token_seconds: float | None = None
    p95_latency_seconds: float | None = None
    error_rate: float = 0.0
    output_tokens_per_dollar: float | None = None
    measured: bool = False
    # Actual counted tokens behind this point; None means the count was not
    # verified and the rates above are approximate at best.
    actual_prompt_tokens: int | None = None
    actual_output_tokens: int | None = None
    sample_count: int | None = None
    # When this point completes successfully: empty requests, truncated
    # generations, and transport fallbacks are not successful completions.
    completion_reason: str | None = None
    cache_policy: CachePolicy = CachePolicy.UNSPECIFIED
    evidence: EvidenceLevel = EvidenceLevel.PREDICTED


@dataclass(frozen=True)
class WorkloadScenario:
    """One reproducible evaluation workload with fixed metric semantics."""

    id: str
    display_name: str
    prompt_tokens: int
    output_tokens: int
    concurrency: int
    request_count: int
    cache_policy: CachePolicy = CachePolicy.UNCACHED
    # Minimum requests before tail percentiles may be reported.
    min_samples_for_p95: int = 20
    # Latency target used to rank interactive recommendations.
    latency_target_seconds: float | None = None
    distinct_prompts: bool = True


@dataclass(frozen=True)
class RuntimeIdentity:
    """Exact runtime configuration behind one observation."""

    model_id: str = ""
    revision: str | None = None
    quant: str | None = None
    runtime_id: str | None = None
    backend: BackendType | None = None
    provider: ComputeProvider | None = None
    gpu_type: str = ""
    gpu_count: int = 1
    server_args: tuple[str, ...] = ()
    effective_flags: tuple[str, ...] = ()


@dataclass(frozen=True)
class MemoryObservation:
    """One per-device memory reading with its source and phase."""

    per_device_used_gb: tuple[float, ...] = ()
    per_device_total_gb: tuple[float, ...] = ()
    source: MemoryObservationSource = MemoryObservationSource.DEVICE_SAMPLE
    phase: str = ""
    # MiB margin the runtime required when this was recorded, if reported.
    margin_mib: int | None = None
    observed_at: str | None = None


@dataclass(frozen=True)
class CompatibilityEvidence:
    """Separately testable compatibility outcomes for one configuration."""

    runtime_supported: EvidenceLevel | None = None
    memory_fit: EvidenceLevel | None = None
    gpu_resident: EvidenceLevel | None = None
    context_executed_tokens: int | None = None
    context_executed_evidence: EvidenceLevel | None = None
    concurrent_capacity: EvidenceLevel | None = None
    service_quality: EvidenceLevel | None = None
    detail: str = ""


@dataclass(frozen=True)
class PredictionSnapshot:
    """What the planner believed before a run, frozen for scoring."""

    estimator_version: str = ""
    raw_per_device_required_gb: tuple[float, ...] = ()
    calibrated_per_device_required_gb: tuple[float, ...] = ()
    predicted_fits: bool = False
    predicted_single_tps: float | None = None
    predicted_aggregate_tps: float | None = None
    recommended: bool = False
    recommendation_reason: str | None = None


@dataclass(frozen=True)
class EvaluationRecord:
    """One frozen prediction paired with its independent observation."""

    record_id: str
    scenario: WorkloadScenario
    runtime: RuntimeIdentity
    prediction: PredictionSnapshot
    outcome: OutcomeKind = OutcomeKind.UNKNOWN
    compatibility: CompatibilityEvidence = field(default_factory=CompatibilityEvidence)
    memory_observations: tuple[MemoryObservation, ...] = ()
    performance: tuple[PerformancePoint, ...] = ()
    price_per_hour_usd: float | None = None
    detail: str = ""
    created_at: str | None = None


@dataclass(frozen=True)
class PlacementAssessment:
    """Planner evidence that a provider placement can satisfy a recipe."""

    fingerprint: str
    memory: MemoryEstimate
    tuning: RuntimeTuning
    performance: tuple[PerformancePoint, ...] = ()
    certification: CertificationState = CertificationState.ESTIMATED
    fits: bool = False
    gpu_resident: bool = False
    rejection_reason: str | None = None
    # Identifies this plan's compute graph without the hardware under it, so
    # one runtime measurement can size every topology that serves it.
    calibration_key: str = ""
    runtime_id: str | None = None


@dataclass(frozen=True)
class RuntimeAttestation:
    """Observed runtime configuration and performance for a live endpoint."""

    fingerprint: str
    requested_context_tokens: int
    effective_context_tokens: int
    gpu_layers: int
    total_layers: int
    gpu_resident: bool
    memory: MemoryEstimate | None = None
    performance: tuple[PerformancePoint, ...] = ()
    runtime_id: str | None = None
    verified_at: str | None = None
    # How ``gpu_resident`` was established. OBSERVED means this runtime, or an
    # earlier run of this exact placement, reported its own offload; PREDICTED
    # means nothing observed it and the planner's expectation stands in. A
    # certificate that cannot say which is a certificate that claims too much.
    residency_evidence: EvidenceLevel | None = None


@dataclass(frozen=True)
class ServingStats:
    """One reading of a serving runtime's own counters and gauges.

    Token counts are whatever the runtime reports, which is always "since this
    process started" -- see :class:`ServingSnapshot` for the totals that
    survive a container restart.
    """

    captured_at: float = 0.0
    prompt_tokens: float | None = None
    generation_tokens: float | None = None
    requests_running: float | None = None
    requests_waiting: float | None = None
    requests_finished: float | None = None
    kv_cache_usage: float | None = None
    avg_ttft_seconds: float | None = None
    # llama.cpp publishes its own decode rate, but as the last request's
    # speed rather than a windowed average, so it reads zero between
    # requests. Kept as a secondary "right now" reading next to the rate
    # derived from counter deltas, which is comparable across backends.
    reported_tokens_per_second: float | None = None
    runtime_started_at: float | None = None

    @property
    def has_readings(self) -> bool:
        """Whether the endpoint answered with metrics this build understands."""
        return any(
            value is not None
            for value in (
                self.prompt_tokens,
                self.generation_tokens,
                self.requests_running,
                self.requests_waiting,
                self.requests_finished,
                self.kv_cache_usage,
            )
        )


@dataclass(frozen=True)
class ServingSnapshot:
    """Live gauges for an endpoint plus its traffic totals across restarts.

    ``observed_at`` is wall-clock time for the reading that produced the live
    gauges. Banked totals loaded without a new request carry the timestamp of
    the reading that banked them (or None when unknown), so passive views can
    present them as history rather than as a current measurement.
    """

    stats: ServingStats = field(default_factory=ServingStats)
    total_prompt_tokens: float = 0.0
    total_generation_tokens: float = 0.0
    tokens_per_second: float | None = None
    observed_at: float | None = None

    @property
    def total_tokens(self) -> float:
        return self.total_prompt_tokens + self.total_generation_tokens


@dataclass
class DeploymentConfig:
    """All parameters needed to execute a deployment.

    Legacy mutable contract, kept for compatibility with persisted jobs and
    existing callers. New code should build a :class:`DeploymentRequest` and
    resolve it to a :class:`ResolvedDeploymentPlan` instead of mutating this.
    """

    backend: BackendType = BackendType.LLAMACPP
    provider: ComputeProvider = ComputeProvider.MODAL

    vision_mode: VisionMode = VisionMode.AUTO
    vision: VisionCapabilities | None = None
    projector_repo: str | None = None
    projector_revision: str | None = None
    projector_file: str | None = None
    image_limit: int = 1
    mm_processor_kwargs: str | None = None

    # llama.cpp specific
    preset: str | None = None
    repo_id: str | None = None
    quant: str | None = None
    revision: str | None = None
    preload: bool = True
    server_args: str | None = None
    host: str | None = None
    port: int | None = None
    n_gpu_layers: int | None = None
    llamacpp_image_no_cache: bool | None = None
    gpu_type: str | None = None
    gpu_count: int | None = None
    required_vram_gb: float | None = None
    gguf_architecture: str | None = None
    llamacpp_runtime_id: str | None = None
    speculative_decoding: SpeculativeDecodingConfig | None = None
    # Whether preflight may resolve speculative decoding from model evidence.
    # ``speculative_decoding`` alone cannot express intent: None is what both a
    # caller with no opinion and a caller that declined leave behind. Preflight
    # treats None as "decide from the GGUF and the pinned runtime" so MTP is on
    # wherever it is supported, and this flag is the only way to say no.
    allow_speculative_decoding: bool = True
    serving_requirements: ServingRequirements | None = None
    runtime_tuning: RuntimeTuning | None = None
    placement_assessment: PlacementAssessment | None = None
    runtime_attestation: RuntimeAttestation | None = None
    # Outcome of the post-warmup tool-call probe: "passed", "failed", or None
    # when it never ran. Coding agents need it to pass.
    tool_calling: str | None = None

    # How many sequences the runtime decodes at once. Left to the image, this
    # differs per provider -- and on a hybrid model a default above the
    # available recurrent-state blocks refuses to start at all.
    max_concurrent_sequences: int | None = None

    # Model limits advertised to OpenAI-compatible clients such as OpenCode.
    max_context_tokens: int | None = None
    max_output_tokens: int | None = None
    reasoning: ReasoningCapabilities | None = None

    # vLLM specific
    model_name: str | None = None
    model_revision: str | None = None
    served_model_name: str | None = None
    fast_boot: bool | None = None
    n_gpu: int | None = None
    trust_remote_code: bool | None = None
    reasoning_parser: str | None = None
    tool_call_parser: str | None = None
    default_chat_template_kwargs: str | None = None

    # Deployment options
    do_deploy: bool = True
    run_smoke: bool = False
    do_warmup: bool = True
    show_debug_logs: bool = False

    # Instance identity
    instance_name: str | None = None
    app_name: str | None = None
    function_slug: str | None = None

    # Provider-specific settings are typed and interpreted only by the adapter.
    provider_options: ProviderOptions | None = None
    endpoint_api_key: str | None = None
    # Quoted execution price for this placement ($/hour), when a quote was
    # selected. Distinct from ``serving_requirements.max_hourly_cost_usd``,
    # which is the approved spending ceiling: a $5/h cap with a $1/h quote
    # must value throughput at $1/h, never at $5/h. ``None`` means unknown.
    price_per_hour_usd: float | None = None
    # Ephemeral Fast Deploy recovery ladder. Provider adapters ignore it.
    fallback_configs: tuple[DeploymentConfig, ...] = ()
    # Explicit lifecycle outcome for one attempt. Replaces mutating
    # ``fallback_configs`` to suppress retries after failed cleanup: the
    # durable worker snapshots the ladder before running, so clearing it could
    # not stop an already-planned next rental.
    retry_allowed: bool = True


@dataclass(frozen=True)
class LlamacppRequestOptions:
    """llama.cpp (GGUF) specific request inputs."""

    preset: str | None = None
    repo_id: str | None = None
    quant: str | None = None
    revision: str | None = None
    preload: bool = True
    server_args: str | None = None
    host: str | None = None
    port: int | None = None
    n_gpu_layers: int | None = None
    llamacpp_image_no_cache: bool | None = None
    gguf_architecture: str | None = None
    llamacpp_runtime_id: str | None = None
    speculative_decoding: SpeculativeDecodingConfig | None = None
    allow_speculative_decoding: bool = True


@dataclass(frozen=True)
class VllmRequestOptions:
    """vLLM specific request inputs."""

    model_name: str | None = None
    model_revision: str | None = None
    served_model_name: str | None = None
    fast_boot: bool | None = None
    n_gpu: int | None = None
    trust_remote_code: bool | None = None
    reasoning_parser: str | None = None
    tool_call_parser: str | None = None
    default_chat_template_kwargs: str | None = None


@dataclass(frozen=True)
class DeploymentRequest:
    """Immutable user intent for one deployment.

    This is the input contract: what the user chose, before resolution fills
    in model evidence, tuning, compiled flags, placement, and identity.
    """

    backend: BackendType = BackendType.LLAMACPP
    provider: ComputeProvider = ComputeProvider.MODAL
    intent: OperationIntent = OperationIntent.SERVE
    do_warmup: bool = True
    show_debug_logs: bool = False
    vision_mode: VisionMode = VisionMode.AUTO
    projector_repo: str | None = None
    projector_revision: str | None = None
    projector_file: str | None = None
    image_limit: int = 1
    mm_processor_kwargs: str | None = None
    llamacpp: LlamacppRequestOptions = field(default_factory=LlamacppRequestOptions)
    vllm: VllmRequestOptions = field(default_factory=VllmRequestOptions)
    gpu_type: str | None = None
    gpu_count: int | None = None
    required_vram_gb: float | None = None
    serving_requirements: ServingRequirements | None = None
    max_context_tokens: int | None = None
    max_output_tokens: int | None = None
    instance_name: str | None = None
    app_name: str | None = None
    function_slug: str | None = None
    provider_options: ProviderOptions | None = None
    cost_scenario_id: str | None = None
    output_tokens_per_month: int | None = None
    # Quoted execution price ($/hour) when a placement quote was selected.
    # Distinct from ``serving_requirements.max_hourly_cost_usd`` (budget cap).
    price_per_hour_usd: float | None = None


@dataclass(frozen=True)
class ResolvedDeploymentPlan:
    """Effective inputs for one deployment attempt, resolved from a request.

    Resolution never mutates the request: discovery, tuning, compiled server
    args, placement, and identity are recorded here.
    """

    request: DeploymentRequest
    backend: BackendType
    provider: ComputeProvider
    intent: OperationIntent
    do_warmup: bool = True
    show_debug_logs: bool = False
    vision: VisionCapabilities | None = None
    projector_repo: str | None = None
    projector_revision: str | None = None
    projector_file: str | None = None
    image_limit: int = 1
    mm_processor_kwargs: str | None = None
    llamacpp: LlamacppRequestOptions = field(default_factory=LlamacppRequestOptions)
    vllm: VllmRequestOptions = field(default_factory=VllmRequestOptions)
    gpu_type: str | None = None
    gpu_count: int | None = None
    required_vram_gb: float | None = None
    serving_requirements: ServingRequirements | None = None
    runtime_tuning: RuntimeTuning | None = None
    placement_assessment: PlacementAssessment | None = None
    reasoning: ReasoningCapabilities | None = None
    max_context_tokens: int | None = None
    max_output_tokens: int | None = None
    instance_name: str | None = None
    app_name: str | None = None
    function_slug: str | None = None
    provider_options: ProviderOptions | None = None
    cost_scenario_id: str | None = None
    output_tokens_per_month: int | None = None
    # Quoted execution price ($/hour) carried with the resolved placement.
    # ``serving_requirements.max_hourly_cost_usd`` remains the budget cap.
    price_per_hour_usd: float | None = None


@dataclass(frozen=True)
class DeploymentAttemptOutcome:
    """Observed result of one deployment attempt."""

    disposition: AttemptDisposition
    resource_app_id: str | None = None
    endpoint_url: str | None = None
    endpoint: EndpointInfo | None = None
    runtime_attestation: RuntimeAttestation | None = None
    failure_detail: str | None = None
    cleanup: CleanupDisposition = CleanupDisposition.UNKNOWN
    cleanup_error: str | None = None
    retry_allowed: bool = True
    failure_exit_code: int | None = None


@dataclass(frozen=True)
class DeploymentResult:
    """Final lifecycle result across attempts."""

    succeeded: bool
    url: str | None = None
    app_name: str | None = None
    attempts: tuple[DeploymentAttemptOutcome, ...] = ()
    outcome: str = ""


@dataclass(frozen=True)
class ProviderCapabilities:
    """Provider features used to filter recipes before requesting quotes."""

    provider: ComputeProvider
    supported_backends: frozenset[BackendType]
    billing_model: BillingModel

    def supports_backend(self, backend: BackendType) -> bool:
        """Return whether this provider can serve the requested runtime."""
        return backend in self.supported_backends


@dataclass(frozen=True)
class InferenceRecipe:
    """Provider-neutral description of a runnable inference configuration."""

    id: str
    model_key: str
    display_name: str
    backend: BackendType
    model_id: str
    quant: str | None = None
    max_context_tokens: int | None = None
    required_vram_gb: float | None = None
    server_args: tuple[str, ...] = ()
    speculative_decoding: SpeculativeDecodingConfig | None = None
    source_label: str = "Curated"
    quality_score: float | None = None
    quality_rank: int | None = None
    serving_requirements: ServingRequirements | None = None
    runtime_tuning: RuntimeTuning | None = None


@dataclass(frozen=True)
class WorkloadProfile:
    """Small workload description used to normalize unlike billing models."""

    paid_hours_per_day: float = 8.0
    utilization: float = 0.25
    output_tokens_per_month: int | None = None


@dataclass(frozen=True)
class CostScenario:
    """Explicit usage assumptions for comparing unlike billing models.

    Provisioned rentals bill for every hour they stay up; scale-to-zero
    providers bill active compute plus idle time while the container stays
    warm. A monthly figure without these assumptions invents a schedule, so
    every scenario names its own.
    """

    id: str
    display_name: str
    provisioned_hours_per_day: float = 24.0
    active_hours_per_day: float = 8.0
    sessions_per_day: float = 4.0
    idle_timeout_seconds: float = 1800.0
    description: str = ""

    def describe(self) -> str:
        """One-line statement of what this scenario assumes."""
        if self.id == "continuous":
            return "Running 24/7 with no shutdown."
        sessions = f"{self.sessions_per_day:g} session(s)/day"
        idle_minutes = self.idle_timeout_seconds / 60.0
        return (
            f"{self.provisioned_hours_per_day:g}h up/day, "
            f"{self.active_hours_per_day:g}h active, {sessions}, "
            f"{idle_minutes:g}min idle timeout."
        )


@dataclass(frozen=True)
class CostEvaluation:
    """One canonical cost calculation for a provider quote.

    Older code carried two different monthly numbers: ``WorkloadProfile``
    normalized scale-to-zero providers by active utilization while
    ``CostScenario`` adds warm idle time between sessions. Plans now store
    this evaluation so stored costs, cost ranking, and cost display share the
    same assumptions.
    """

    scenario: CostScenario
    billed_hours_per_day: float
    estimated_monthly_cost_usd: float | None = None
    continuous_monthly_cost_usd: float | None = None
    estimated_cost_per_million_output_tokens_usd: float | None = None
    cost_basis: str = ""
    # Vast folds disk rent into its quoted hourly total, so the generic
    # "storage excluded" label is wrong for it. Quotes keep the truth here.
    includes_storage: bool = False
    output_tokens_per_month: int | None = None
    idle_timeout_seconds: float | None = None

    def basis_label(self) -> str:
        """State the effective assumptions behind this evaluation."""
        timeout = (
            self.idle_timeout_seconds
            if self.idle_timeout_seconds is not None
            else self.scenario.idle_timeout_seconds
        )
        idle_minutes = timeout / 60.0
        return (
            f"Cost scenario '{self.scenario.display_name}': "
            f"{self.scenario.provisioned_hours_per_day:g}h up/day, "
            f"{self.scenario.active_hours_per_day:g}h active, "
            f"{self.scenario.sessions_per_day:g} session(s)/day, "
            f"{idle_minutes:g}min idle timeout."
        )


@dataclass(frozen=True)
class ProviderQuote:
    """Normalized provider fulfillment option for an inference recipe."""

    id: str
    recipe_id: str
    provider: ComputeProvider
    provider_reference: str
    gpu_type: str
    gpu_count: int
    price_per_hour_usd: float | None
    billing_model: BillingModel
    gpu_memory_gb: float | None = None
    availability: QuoteAvailability = QuoteAvailability.UNKNOWN
    region: str | None = None
    security: str | None = None
    is_estimate: bool = True
    estimated_output_tokens_per_second: float | None = None
    configuration_id: str | None = None
    provider_options: ProviderOptions | None = None


@dataclass(frozen=True)
class InferencePlan:
    """One deployable recipe bound to a compatible provider quote."""

    recipe: InferenceRecipe
    quote: ProviderQuote
    estimated_monthly_cost_usd: float | None = None
    estimated_cost_per_million_output_tokens_usd: float | None = None
    recommendation_reason: str | None = None
    assessment: PlacementAssessment | None = None
    # Canonical cost calculation, attached so ranking and display cannot drift
    # apart. Legacy plans built before this field existed keep the two cached
    # monthly/token fields above; treat them as assumption-free estimates.
    cost: CostEvaluation | None = None


@dataclass(frozen=True)
class ComputePlacement:
    """One provider fulfillment option behind an aggregated GPU type."""

    id: str
    provider: ComputeProvider
    provider_reference: str
    gpu_type: str
    gpu_memory_gb: float
    gpu_count_min: int
    gpu_count_max: int
    price_per_hour_usd: float | None
    billing_model: BillingModel
    availability: QuoteAvailability
    supported_backends: frozenset[BackendType]
    region: str | None = None
    security: str | None = None
    is_estimate: bool = False
    price_is_per_gpu: bool = False
    is_spot: bool = False
    provider_options: ProviderOptions | None = None


@dataclass(frozen=True)
class ComputeConfiguration:
    """Provider-neutral GPU type with all compatible fulfillment placements."""

    id: str
    gpu_type: str
    gpu_memory_gb: float
    placements: tuple[ComputePlacement, ...]

    def _fulfillable_placements(self) -> tuple[ComputePlacement, ...]:
        """Return deployable rows, falling back to spot-only catalogs."""

        deployable = tuple(row for row in self.placements if not row.is_spot)
        return deployable or self.placements

    @property
    def gpu_count_min(self) -> int:
        return min(
            (row.gpu_count_min for row in self._fulfillable_placements()),
            default=1,
        )

    @property
    def gpu_count_max(self) -> int:
        return max(
            (row.gpu_count_max for row in self._fulfillable_placements()),
            default=1,
        )

    @property
    def total_vram_max_gb(self) -> float:
        return self.gpu_memory_gb * self.gpu_count_max

    @property
    def live_placement_count(self) -> int:
        return sum(
            row.availability == QuoteAvailability.AVAILABLE and not row.is_spot
            for row in self.placements
        )

    @property
    def has_on_demand_capacity(self) -> bool:
        return any(
            row.availability == QuoteAvailability.UNKNOWN and not row.is_spot
            for row in self.placements
        )

    @property
    def spot_placement_count(self) -> int:
        return sum(row.is_spot for row in self.placements)

    @property
    def source_count(self) -> int:
        return len({row.provider for row in self.placements})

    @property
    def regions(self) -> tuple[str, ...]:
        return tuple(
            sorted(
                {
                    row.region.strip()
                    for row in self.placements
                    if row.region and row.region.strip()
                },
                key=str.casefold,
            )
        )

    @property
    def minimum_price_per_hour_usd(self) -> float | None:
        prices = [
            row.price_per_hour_usd
            for row in self._fulfillable_placements()
            if row.price_per_hour_usd is not None
        ]
        return min(prices) if prices else None


@dataclass(frozen=True)
class ComputeAvailabilitySnapshot:
    """Aggregated compute availability plus connected provider metadata."""

    configurations: tuple[ComputeConfiguration, ...]
    errors: tuple[str, ...] = ()
    providers: tuple[ComputeProvider, ...] | None = None
    vast_offers: tuple[VastOffer, ...] = ()
    vast_configured: bool = False


@dataclass
class EndpointInfo:
    """A single row from `modal app list`."""

    name: str = ""
    app_id: str = ""
    state: str = "unknown"
    backend: BackendType | None = None
    instance_name: str | None = None
    web_url: str | None = None
    served_model_name: str | None = None
    display_name: str | None = None
    model_name: str | None = None
    repo_id: str | None = None
    quant: str | None = None
    runtime_status: str | None = None
    runtime_status_detail: str | None = None
    # Wall-clock epoch of the last explicit (user-requested) runtime health
    # observation. Passive fleet refreshes never touch the network for
    # scale-to-zero providers, so they re-attach the stored verdict and show
    # its age instead of claiming the deployment itself is healthy.
    runtime_checked_at: float | None = None
    provider: ComputeProvider = ComputeProvider.MODAL
    endpoint_api_key: str | None = None
    max_context_tokens: int | None = None
    max_output_tokens: int | None = None
    reasoning: ReasoningCapabilities | None = None
    vision: VisionCapabilities | None = None
    runtime_attestation: RuntimeAttestation | None = None
    tool_calling: str | None = None
    serving: ServingSnapshot | None = None
    # Wall-clock epoch the current container/process run started. Sourced
    # from the runtime's own process start gauge when a live reading exists;
    # otherwise the first passive observation of the active run. Resets on
    # restart; None when the run start cannot be established (notably a
    # scale-to-zero Modal app with no live probe). Never deployment age.
    run_started_at_epoch: float | None = None
    # Known billable rate for this endpoint ($/hour). Persisted from the
    # deployment quote via the connection store, or from provider listing
    # metadata when available. None means the rate is unknown, never free.
    hourly_cost_usd: float | None = None
    # Accumulated compute cost across runs ($). Persisted by the runtime
    # tracker; None when no billable interval has been observed with a known
    # rate.
    cumulative_cost_usd: float | None = None
    # Whether the accumulated cost is an estimate (rate changes, capped
    # scale-to-zero gaps, or missed observations) rather than a metered bill.
    cost_estimated: bool = False
    # Wall-clock epoch cost tracking started for this endpoint. Gaps before
    # this (redeploys, TUI restarts before tracking) are not included, so a
    # total without this is never presented as complete.
    cost_tracked_since_epoch: float | None = None
    # Last explicit live-metrics attempt (user-requested fetch that may wake
    # a scaled-to-zero container). Failures retain banked totals and surface
    # here instead of blanking the traffic columns.
    live_metrics_error: str | None = None
    live_metrics_checked_at: float | None = None


@dataclass
class BenchmarkConfig:
    """Parameters for benchmarking a deployed OpenAI-compatible endpoint."""

    backend: BackendType = BackendType.LLAMACPP
    provider: ComputeProvider = ComputeProvider.MODAL
    app_name: str | None = None
    instance_name: str | None = None
    server_url: str | None = None
    model_name: str | None = None
    concurrency: list[int] = field(default_factory=lambda: [1, 2, 4, 8, 16])
    request_count: int | None = None
    input_tokens: int = 550
    output_tokens: int = 256
    tokenizer: str = "gpt2"
    request_timeout_seconds: int = 300
    output_dir: str | None = None
    aiperf_args: list[str] = field(default_factory=list)
    api_key: str | None = None


@dataclass(frozen=True)
class ComputeOffer:
    """Normalized GPU offer exposed by a compute provider."""

    id: str
    cloud_id: str
    provider_name: str
    gpu_type: str
    gpu_count: int
    gpu_memory_gb: float | None = None
    region: str | None = None
    data_center: str | None = None
    country: str | None = None
    socket: str | None = None
    security: str | None = None
    price_per_hour: float | None = None
    is_spot: bool = False
    is_variable_price: bool = False
    stock_status: str | None = None
    disk_default_gb: int | None = None
    vcpu_default: int | None = None
    memory_default_gb: int | None = None
    images: tuple[str, ...] = ()
    raw: dict[str, Any] = field(default_factory=dict, repr=False, compare=False)


@dataclass(frozen=True)
class VastAuthStatus:
    """Account validation result; configured credentials alone are not auth."""

    authenticated: bool
    source: str = "none"
    account_id: str | None = None
    error: str | None = None


@dataclass(frozen=True)
class VastOfferQuery:
    """Constraints for read-only discovery of verified on-demand rentals."""

    gpu_type: str | None = None
    # None discovers topologies with one through eight GPUs for Fast Deploy.
    gpu_count: int | None = 1
    country: str | None = None
    disk_gb: int = 100
    min_reliability: float = 0.99
    datacenter_only: bool = False
    limit: int = 100


@dataclass(frozen=True)
class OfferCostBreakdown:
    """Provider-quoted hourly and transfer prices; missing is not free."""

    compute_per_hour_usd: float | None = None
    disk_per_hour_usd: float | None = None
    total_per_hour_usd: float | None = None
    download_per_gb_usd: float | None = None
    upload_per_gb_usd: float | None = None


@dataclass(frozen=True)
class MemoryUnits:
    """One documented conversion between planner GiB and a provider display unit.

    Internal fit math stays in binary GiB, matching llama.cpp's MiB fit rows.
    Anything quoting memory another way converts at the boundary through one
    of these definitions instead of an inline ``/ 1000`` or ``/ 1024``.
    """

    id: str
    display_name: str
    gib_per_unit: float


#: Vast marketplace rows quote raw MiB straight from the API.
VAST_RAW_MIB = MemoryUnits(id="vast-raw-mib", display_name="Vast raw MiB", gib_per_unit=1.0 / 1024.0)
#: Vast marketplace browser labels divide those MiB by 1000, mirroring the
#: official CLI display convention.
VAST_DISPLAY_GB = MemoryUnits(
    id="vast-display-gb", display_name="Vast display GB", gib_per_unit=1000.0 / 1024.0
)
#: Hugging Face file sizes and Modal catalog capacities are decimal GB.
DECIMAL_GB = MemoryUnits(id="gb", display_name="GB", gib_per_unit=1.0 / 1.073741824)
#: Runtime measurements and planner reserves are binary GiB.
BINARY_GIB = MemoryUnits(id="gib", display_name="GiB", gib_per_unit=1.0)


def convert_memory(value: float, source: MemoryUnits, target: MemoryUnits) -> float:
    """Convert a memory quantity between two documented units."""
    return value * source.gib_per_unit / target.gib_per_unit


def vast_raw_mib_to_display_gb(raw_mib: float) -> float:
    """Render a Vast ``gpu_ram`` reading the way the marketplace browser does."""
    return convert_memory(raw_mib, VAST_RAW_MIB, VAST_DISPLAY_GB)


@dataclass(frozen=True)
class VastOffer:
    """Normalized marketplace rental; not a certified inference placement.

    ``gpu_memory_gb`` carries Vast's decimal display units (raw MiB / 1000),
    matching the offer browser. Use ``gpu_memory_gib`` for planner fit math,
    which compares against runtime measurements in binary GiB.
    """

    id: str
    machine_id: str
    gpu_type: str
    gpu_count: int
    gpu_memory_gb: float
    reliability: float
    disk_gb: int
    costs: OfferCostBreakdown
    location: str = ""
    datacenter: bool = False
    cpu_memory_gb: float | None = None
    max_duration_hours: float | None = None
    disk_capacity_gb: float | None = None
    cuda_max_good: float | None = None
    # A modern driver on an old card still cannot run a modern CUDA build:
    # CUDA 13 dropped Maxwell, Pascal and Volta.
    compute_capability: float | None = None
    # Pulling a multi-gigabyte runtime image is often the slowest part of a
    # rental's startup, and marketplace links vary by an order of magnitude.
    inet_down_mbps: float | None = None

    @property
    def gpu_memory_gib(self) -> float:
        """Convert Vast's decimal display GB back to binary GiB for fit math."""
        return convert_memory(self.gpu_memory_gb, VAST_DISPLAY_GB, BINARY_GIB)


@dataclass(frozen=True)
class VastModelOffer:
    """Model-sized rental comparison, deliberately separate from deployable plans."""

    id: str
    recipe: InferenceRecipe
    offer: VastOffer
    gpu_label: str
    disk_gb: int
    costs: OfferCostBreakdown
    assessment: PlacementAssessment


@dataclass(frozen=True)
class VastInstance:
    """Non-secret instance identity and SSH connection metadata."""

    id: str
    label: str
    state: str
    machine_id: str
    ssh_host: str = ""
    ssh_port: int = 0
    # Vast's own provisioning progress line. The deploy loop uses it to tell a
    # slow host from a stuck one; ``state`` alone sits on "loading" throughout.
    status_msg: str = ""


@dataclass
class VastDeploymentRecord:
    """Durable rental intent retained until remote destruction is confirmed."""

    name: str
    label: str
    account_id: str
    offer_id: str
    machine_id: str
    repo_id: str
    quant: str
    served_model_name: str
    endpoint_api_key: str = field(repr=False)
    instance_id: str | None = None
    local_port: int = 0
    state: str = "creating"
    max_context_tokens: int | None = None
    # Defaults keep records written before Vast served vLLM readable.
    backend: str = "llamacpp"
    model_name: str = ""


@dataclass
class BenchmarkConcurrencyResult:
    """Benchmark result for one concurrency value."""

    concurrency: int
    command: list[str]
    artifact_dir: str
    exit_code: int = 0
    success: bool = True
    detail: str = ""
    metrics: dict[str, float | None] = field(default_factory=dict)


@dataclass
class BenchmarkRunSummary:
    """Summary of a benchmark sweep."""

    config: BenchmarkConfig
    run_dir: str
    results: list[BenchmarkConcurrencyResult] = field(default_factory=list)
    success: bool = True
    best_concurrency: int | None = None
    best_output_token_throughput: float | None = None


@dataclass
class StoredModelInfo:
    """Single cached model entry in Modal storage."""

    backend: BackendType
    model_id: str
    revision: str | None = None
    quant: str | None = None
    size_bytes: int = 0
    file_count: int = 0
    source_volume: str = ""
    paths: list[str] | None = None
    incomplete: bool = False


@dataclass
class StorageSnapshot:
    """Cached model inventory grouped by backend."""

    llamacpp_models: list[StoredModelInfo]
    vllm_models: list[StoredModelInfo]

    @property
    def total_size_bytes(self) -> int:
        return sum(row.size_bytes for row in self.llamacpp_models + self.vllm_models)

    @property
    def total_models(self) -> int:
        return len(self.llamacpp_models) + len(self.vllm_models)


@dataclass(frozen=True)
class StopEffect:
    """What stopping one deployment's compute does to its storage and bill."""

    provider: ComputeProvider
    compute_action: str
    storage_consequence: str
    remains_billable: bool
    destructive: bool
    detail: str = ""
    recovery_hint: str = ""


@dataclass(frozen=True)
class ProviderListing:
    """One provider's answer to a fleet discovery pass.

    A provider that could not be reached still contributes the rows it last
    returned. An empty fleet and an unreachable provider mean opposite things
    to someone deciding whether to redeploy, so the two are never merged into
    a shorter list.
    """

    provider: ComputeProvider
    rows: tuple[EndpointInfo, ...] = ()
    error: str | None = None
    retrieved_at_epoch: float | None = None

    @property
    def available(self) -> bool:
        """Whether this pass reached the provider."""
        return self.error is None

    @property
    def is_retained(self) -> bool:
        """Whether these rows survived a failed pass and may be out of date."""
        return self.error is not None and bool(self.rows)

    def age_seconds(self, now: float) -> float | None:
        """Seconds since these rows were read, or None if they never were."""
        if self.retrieved_at_epoch is None:
            return None
        return max(0.0, now - self.retrieved_at_epoch)


@dataclass(frozen=True)
class FleetDiscovery:
    """Every configured provider's listing from a single discovery pass."""

    listings: tuple[ProviderListing, ...] = ()

    @property
    def rows(self) -> list[EndpointInfo]:
        return [row for listing in self.listings for row in listing.rows]

    @property
    def prune_providers(self) -> tuple[ComputeProvider, ...]:
        """Providers that answered, and whose absences are therefore real."""
        return tuple(listing.provider for listing in self.listings if listing.available)

    @property
    def unavailable(self) -> tuple[ProviderListing, ...]:
        return tuple(listing for listing in self.listings if not listing.available)
