"""Regenerate docs/cli.md from the live Typer CLI help output.

Usage:
    uv run python scripts/generate_cli_reference.py

Captures ``--help`` for every command and subcommand and renders a single
Markdown page. Re-run whenever a CLI command changes; the output is
committed so the repository docs stay in sync without extra tooling.
"""

from __future__ import annotations

import click
import os
from pathlib import Path
import subprocess
import sys

import typer.main

from llm_launchpad.cli.main import app as cli_app

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "cli.md"
COLUMNS = "100"

HEADER = """<!-- Generated by scripts/generate_cli_reference.py. Do not edit by hand. -->

# CLI reference

Complete `llm-launchpad` command reference, generated from `--help` output.
Run `uv run python scripts/generate_cli_reference.py` after changing a command.

"""


def command_paths(command: click.Command, prefix: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    """Yield the argv path of every leaf command in the click tree."""

    paths: list[tuple[str, ...] | None] = []
    subcommands = getattr(command, "commands", None)
    if not subcommands:
        if prefix:
            return [prefix]
        return []
    for name in sorted(subcommands):
        paths.extend(command_paths(subcommands[name], (*prefix, name)))
    return [path for path in paths if path is not None]


def render_help(path: tuple[str, ...]) -> str:
    """Run one command's ``--help`` through the real entrypoint."""

    argv = [sys.executable, "-m", "llm_launchpad.cli.main", *path, "--help"]
    env = {**os.environ, "COLUMNS": COLUMNS}
    result = subprocess.run(
        argv,
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    output = (result.stdout or result.stderr).rstrip()
    if result.returncode != 0 or not output:
        raise RuntimeError(
            f"Failed to render help for {' '.join(path)}: exit {result.returncode}\n{result.stderr}"
        )
    return output


def slug_for(path: tuple[str, ...]) -> str:
    return "-".join(("llm-launchpad", *path))


def clean_help(text: str) -> str:
    """Normalize rendered help for Markdown embedding."""

    normalized = text.replace(
        "Usage: python -m llm_launchpad.cli.main", "Usage: llm-launchpad"
    )
    return "\n".join(line.rstrip() for line in normalized.splitlines())


def main() -> None:
    root = typer.main.get_command(cli_app)
    paths = [()] + command_paths(root)
    if len(paths) <= 1:
        raise RuntimeError("No CLI commands discovered")

    toc: list[str] = ["## Commands", ""]
    sections: list[str] = []

    for path in paths:
        label = " ".join(("llm-launchpad", *path)).strip()
        toc.append(f"- [`{label}`](#{slug_for(path)})")
    toc.append("")

    for path in paths:
        label = " ".join(("llm-launchpad", *path)).strip()
        sections.append(f"## `{label}`\n\n```text\n{clean_help(render_help(path))}\n```\n")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(HEADER + "\n".join(toc) + "\n" + "\n".join(sections), encoding="utf-8")
    print(f"Wrote {len(paths)} command sections to {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
