name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  package-checks:
    name: Package checks
    uses: ./.github/workflows/package-checks.yml
    permissions:
      contents: read
